#!/bin/sh


HD='sda3'


# ADD AUR TO PACMAN.CONF ---------------------------------------------------------------------
echo "----> adding AUR to /etc/pacman.conf"
archfr='\n[archlinuxfr]\nSigLevel = Optional TrustAll\nServer = http://repo.archlinux.fr/$arch'
echo -e $archfr | sudo tee -a /etc/pacman.conf


# ADD STORAGE TO FSTAB ---------------------------------------------------------------------
echo "----> adding storage to /etc/pacman.conf"
storage="\n# mounting storage here\n/dev/$HD  /storage  ntfs-3g   uid=dava,gid=users,dmask=022,fmask=133	 0 0"
echo -e $storage | sudo tee -a /etc/fstab
