#!/bin/sh

pm='yaourt -S --noconfirm'

apps=(

	# main
 	chromium-pepper-flash
 	urxvt-tabbedex
 	powerpill
 	compton-git

 	# themes & icons
 	zukitwo-themes
 	gnome-colors-icon-theme gnome-colors-icon-theme-extras 
 	faenza-cupertino-icon-theme 
 	clarity-icon-theme tango-icon-theme
 	notify-osd-customizable notifyconf


)
 
for app in "${apps[@]}"
do
	query=$(pacman -Q $app 2>&1)
	if [ ${query:0:5} == "error" ]; then
		echo "------------------------------------------------------" 
		echo "----> Installing " $app
		echo "------------------------------------------------------"
		$pm $app
	fi

done




























 # if [ ${query:0:5} == "error" ]; then
 # 	echo "app is not installed"

 # fi

# INSTALLATION -------------------------------------------
# sudo $pm  libreoffice
# sudo $pm --needed $main 
# sudo $pm --needed $audio
# sudo $pm --needed $theme
# sudo $pm --needed $font
# sudo $pm --needed $games