#!/bin/sh

home='/home/dava/.arch-configs/homepc/home'
homeConfig='/home/dava/.arch-configs/homepc/home/config'
rootConfig='/home/dava/.arch-configs/homepc/root'
shortcut='/home/dava/.arch-configs/homepc/shortcuts'


# HOME LINKS -----------------------------------------------------------------
echo "# HOME LINKS"

if ls /home/dava/.xinitrc &> /dev/null; then
	echo "----> found existing .xinitrc removing..."
	rm /home/dava/.xinitrc
fi

if ls /home/dava/.Xresources &> /dev/null; then
	echo "----> found existing .Xresources removing..."
	rm /home/dava/.Xresources
fi

if ls /home/dava/.asoundrc &> /dev/null; then
	echo "----> found existing .asoundrc removing..."
	rm /home/dava/.asoundrc
fi

echo "----> linking .xinitrc"
ln -s $home/xinitrc /home/dava/.xinitrc
echo "----> linking .Xresources"
ln -s $home/Xresources /home/dava/.Xresources
echo "----> linking .asoundrc"
ln -s $home/asoundrc /home/dava/.asoundrc
printf "\n\n"


# CONFIG LINKS -----------------------------------------------------------------
echo "# CONFIG LINKS"

if ls /home/dava/.config/sublime-text-3/Packages/User/* &> /dev/null; then
	echo "----> found existing sublime settings removing..."
	rm -r -R /home/dava/.config/sublime-text-3/Packages/User/*
fi

if [ -h /home/dava/.asoundrc ]; then
	echo "----> found existing compton config removing..."
	rm /home/dava/.config/compton.conf
fi

if ls /home/dava/.config/openbox &> /dev/null; then
	echo "----> found existing openbox settings removing..."
	rm -rf -R /home/dava/.config/openbox
fi

if ls /home/dava/.config/user-dirs.dirs &> /dev/null; then
	echo "----> found existing user-dirs removing..."
	rm /home/dava/.config/user-dirs.dirs
fi

# sublime
echo "----> linking sublime settings"
ln -s $homeConfig/sublime/settings /home/dava/.config/sublime-text-3/Packages/User/Preferences.sublime-settings
ln -s $homeConfig/sublime/keymap /home/dava/.config/sublime-text-3/Packages/User/Default\ \(Linux\).sublime-keymap

# compton
echo "----> linking compton.conf"
ln -s $homeConfig/compton.conf /home/dava/.config/compton.conf

# openbox
echo "----> linking openbox settings"
ln -s $homeConfig/openbox /home/dava/.config/openbox

# users-dir
echo "----> linking user-dirs"
ln -s $homeConfig/user-dirs.dirs /home/dava/.config/user-dirs.dirs

printf "\n\n"


# SHORTCUTS LINK -----------------------------------------------------------------
echo "# SHORTCUT LINKS"

if ls /home/dava/.2shortcuts &> /dev/null; then
	echo "----> found existing shortcuts removing..."
	rm -rf -R /home/dava/.2shortcuts
fi
echo "----> linking shortcuts"
ln -s $shortcut /home/dava/.2shortcuts
printf "\n\n"


# ROOT LINKS ---------------------------------------------------------------------
echo "# COPY ROOT CONFIGS"

echo "----> copying oblogout.conf"
sudo cp $rootConfig/oblogout.conf /etc/

echo "----> copying pinter filters"
sudo cp $rootConfig/printer/rastertosag-gdi /usr/lib/cups/filter/
sudo chmod 755 /usr/lib/cups/filter/rastertosag-gdi

sudo cp $rootConfig/printer/rastertosag-gdi.drv /usr/share/cups/drv/
sudo chmod 644 /usr/share/cups/drv/rastertosag-gdi.drv

echo "----> copying pwmconfig"
sudo cp $rootConfig/fancontrol /etc/

printf "\n\n"